---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/redhat-appstudio/build-definitions/main/task/git-clone/0.1/git-clone.yaml
  - https://raw.githubusercontent.com/redhat-appstudio/build-definitions/main/task/buildah/0.1/buildah.yaml

patches:
  - target:
      kind: Task
      name: git-clone
    patch: |-
      ---
      - op: add
        path: /spec/results/-
        value:
          name: SOURCE_ARTIFACT
          type: string
          description: Produced trusted artifact
      - op: add
        path: /spec/steps/-
        value:
          name: create-trusted-artifact
          image: ${repository}/build-trusted-artifacts
          args:
            - create
            - --store 
            - quay.io/jstuart/trusted-artifacts
            - $(results.SOURCE_ARTIFACT.path)=$(workspaces.output.path)/$(params.subdirectory)
  - target:
      kind: Task
      name: buildah
    patch: |-
      ---
      - op: add
        path: /spec/params/-
        value:
          name: SOURCE_ARTIFACT
          type: string
      - op: add
        path: /spec/steps/0
        value:
          name: use-trusted-artifact
          image: ${repository}/build-trusted-artifacts
          args:
            - use
            - $(params.SOURCE_ARTIFACT)=$(workspaces.source.path)/source
